2018-05-02 14:03:34,408 [ERROR] Database unavailable
Traceback (most recent call last):
  File "/home/aman/Documents/aman/personal_repo/flask-restful-boilerplate/src/instance/flask_app.py", line 23, in <module>
    connection = DataBase().get()
  File "/home/aman/Documents/aman/personal_repo/flask-restful-boilerplate/src/core/db_connection.py", line 8, in __init__
    self.connection = psycopg2.connect(config['database']['db_url'])
  File "/home/aman/Desktop/Drive/venvs/flask-restful-boilerplate/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "scott"
FATAL:  password authentication failed for user "scott"

2018-05-02 14:11:05,792 [INFO ] service started at 0.0.0.0:5000
2018-05-02 14:11:06,202 [INFO ] service started at 0.0.0.0:5000
2018-05-02 15:06:44,875 [INFO ] service started at 0.0.0.0:5000
2018-05-02 15:06:45,302 [INFO ] service started at 0.0.0.0:5000
2018-05-02 15:15:33,276 [INFO ] service started at 0.0.0.0:5000
2018-05-02 15:15:33,607 [INFO ] service started at 0.0.0.0:5000
2018-05-02 15:15:46,711 [INFO ] testing accessibility of users endpoint
2018-05-02 15:15:51,758 [INFO ] testing accessibility of products endpoint
2018-05-02 15:20:50,857 [INFO ] service started at 0.0.0.0:5000
2018-05-02 15:20:51,154 [INFO ] service started at 0.0.0.0:5000
